### ISSUE TITLE
Check equation

### ISSUE THREAD

**Issue by dyna2gams** [auralius/waterhammer#1]
I suspect equation 
```v(1) = v(1) + dt * ( 1/rho*dl*(P-p(2)) - f/(2*D)*v(1)*abs(v(1)) )```
in files waterhammer_{lo,hi}_time_res.m should read
```v(1) = v(1) + dt * ( 1/(rho*dl)*(P-p(2)) - f/(2*D)*v(1)*abs(v(1)) )```
Cheers
AMi

**Comment by auralius** [comment]
Yes, you are right! Thanks a lot!
